import type { ProduceItem } from "./types";

export const PRODUCE = [
    // Fruits
    { value: 'apple', label: 'Apple (Seb)', icon: '🍎' },
    { value: 'apricot', label: 'Apricot (Khubani)', icon: '🍑' },
    { value: 'avocado', label: 'Avocado', icon: '🥑' },
    { value: 'banana', label: 'Banana (Kela)', icon: '🍌' },
    { value: 'blackberry', label: 'Blackberry', icon: '🫐' },
    { value: 'blueberry', label: 'Blueberry', icon: '🫐' },
    { value: 'cantaloupe', label: 'Cantaloupe', icon: '🍈' },
    { value: 'cherry', label: 'Cherry', icon: '🍒' },
    { value: 'coconut', label: 'Coconut (Nariyal)', icon: '🥥' },
    { value: 'cranberry', label: 'Cranberry', icon: '🔴' },
    { value: 'custardapple', label: 'Custard Apple (Sitaphal)', icon: '🍈' },
    { value: 'date', label: 'Date (Khajoor)', icon: '🟤' },
    { value: 'dragonfruit', label: 'Dragonfruit', icon: '🐉' },
    { value: 'durian', label: 'Durian', icon: '🍈' },
    { value: 'fig', label: 'Fig (Anjeer)', icon: '🌰' },
    { value: 'gooseberry', label: 'Gooseberry (Amla)', icon: '🟢' },
    { value: 'grape', label: 'Grape (Angoor)', icon: '🍇' },
    { value: 'grapefruit', label: 'Grapefruit', icon: '🍊' },
    { value: 'guava', label: 'Guava (Amrood)', icon: '🍐' },
    { value: 'honeydew', label: 'Honeydew Melon', icon: '🍈' },
    { value: 'jackfruit', label: 'Jackfruit (Kathal)', icon: '🍈' },
    { value: 'jujube', label: 'Jujube (Ber)', icon: '🌰' },
    { value: 'kiwi', label: 'Kiwifruit', icon: '🥝' },
    { value: 'kumquat', label: 'Kumquat', icon: '🍊' },
    { value: 'lemon', label: 'Lemon / Lime (Nimbu)', icon: '🍋' },
    { value: 'lime', label: 'Lime', icon: '🍋' },
    { value: 'litchi', label: 'Litchi / Lychee', icon: '🍒' },
    { value: 'mango', label: 'Mango (Aam)', icon: '🥭' },
    { value: 'mangosteen', label: 'Mangosteen', icon: '🟣' },
    { value: 'muskmelon', label: 'Muskmelon (Kharbooja)', icon: '🍈' },
    { value: 'nectarine', label: 'Nectarine', icon: '🍑' },
    { value: 'orange', label: 'Orange (Santra)', icon: '🍊' },
    { value: 'papaya', label: 'Papaya (Papita)', icon: '🍈' },
    { value: 'passionfruit', label: 'Passionfruit', icon: '🟣' },
    { value: 'peach', label: 'Peach (Aadoo)', icon: '🍑' },
    { value: 'pear', label: 'Pear (Nashpati)', icon: '🍐' },
    { value: 'persimmon', label: 'Persimmon', icon: '🟠' },
    { value: 'pineapple', label: 'Pineapple (Ananas)', icon: '🍍' },
    { value: 'plum', label: 'Plum (Aloo Bukhara)', icon: '🍑' },
    { value: 'pomegranate', label: 'Pomegranate (Anar)', icon: '🔴' },
    { value: 'quince', label: 'Quince', icon: '🍐' },
    { value: 'raspberry', label: 'Raspberry', icon: '🍓' },
    { value: 'rambutan', label: 'Rambutan', icon: '🍒' },
    { value: 'sapota', label: 'Sapota (Chikoo)', icon: '🥝' },
    { value: 'starfruit', label: 'Starfruit (Kamrakh)', icon: '🌟' },
    { value: 'strawberry', label: 'Strawberry', icon: '🍓' },
    { value: 'sweetlime', label: 'Sweet Lime (Mausambi)', icon: '🍋' },
    { value: 'tamarind', label: 'Tamarind (Imli)', icon: '🟤' },
    { value: 'tangerine', label: 'Tangerine', icon: '🍊' },
    { value: 'watermelon', label: 'Watermelon (Tarbooz)', icon: '🍉' },
    { value: 'woodapple', label: 'Wood Apple (Bel)', icon: '🥥' },
    // Vegetables
    { value: 'artichoke', label: 'Artichoke', icon: '🥬' },
    { value: 'asparagus', label: 'Asparagus', icon: '🌿' },
    { value: 'beetroot', label: 'Beetroot (Chukandar)', icon: '🟣' },
    { value: 'bell_pepper', label: 'Bell Pepper (Shimla Mirch)', icon: '🫑' },
    { value: 'broccoli', label: 'Broccoli', icon: '🥦' },
    { value: 'brussels_sprout', label: 'Brussels Sprout', icon: '🥬' },
    { value: 'cabbage', label: 'Cabbage (Patta Gobhi)', icon: '🥬' },
    { value: 'carrot', label: 'Carrot (Gajar)', icon: '🥕' },
    { value: 'cauliflower', label: 'Cauliflower (Phool Gobhi)', icon: '🥦' },
    { value: 'celery', label: 'Celery', icon: '🥬' },
    { value: 'corn', label: 'Corn (Bhutta)', icon: '🌽' },
    { value: 'cucumber', label: 'Cucumber (Kheera)', icon: '🥒' },
    { value: 'eggplant', label: 'Eggplant (Baingan)', icon: '🍆' },
    { value: 'garlic', label: 'Garlic (Lehsun)', icon: '🧄' },
    { value: 'ginger', label: 'Ginger (Adrak)', icon: '🫚' },
    { value: 'green_bean', label: 'Green Bean', icon: '🫛' },
    { value: 'kale', label: 'Kale', icon: '🥬' },
    { value: 'leek', label: 'Leek', icon: '🥬' },
    { value: 'lettuce', label: 'Lettuce', icon: '🥬' },
    { value: 'mushroom', label: 'Mushroom', icon: '🍄' },
    { value: 'okra', label: 'Okra (Bhindi)', icon: '🥬' },
    { value: 'onion', label: 'Onion (Pyaz)', icon: '🧅' },
    { value: 'parsnip', label: 'Parsnip', icon: '🥕' },
    { value: 'pea', label: 'Pea (Matar)', icon: '🫛' },
    { value: 'potato', label: 'Potato (Aloo)', icon: '🥔' },
    { value: "pumpkin", label: "Pumpkin (Kaddu)", icon: "🎃" },
    { value: "radish", label: "Radish (Mooli)", icon: "🔴" },
    { value: "spinach", label: "Spinach (Palak)", icon: "🥬" },
    { value: "squash", label: "Squash", icon: "🎃" },
    { value: "sweet_potato", label: "Sweet Potato (Shakarkandi)", icon: "🍠" },
    { value: "tomato", label: "Tomato (Tamatar)", icon: "🍅" },
    { value: "turnip", label: "Turnip (Shalgam)", icon: "🌱" },
    { value: "zucchini", label: "Zucchini", icon: "🥒" },
    { value: 'jamun', label: 'Black Plum (Jamun)', icon: '🫐' },
    { value: 'waterchestnut', label: 'Water Chestnut (Singhara)', icon: '🌰' }
] as const;